# baseURL
@baseURL = http://localhost:3000

###
# Find All posts
GET {{ baseURL }}/posts?skip=3&take=3

###
# Find Post By Id
GET {{ baseURL }}/posts/1

###
# Create Post
POST {{ baseURL }}/posts
Content-Type: application/json

{
    "message": "Hello wold"
}

###
# Like Post
PATCH {{ baseURL }}/posts/1/like
Content-Type: application/json

###
# Modify Post By Id
PUT {{ baseURL }}/posts/1
Content-Type: application/json

{
    "message": "Hello wold 2"
}

###
# Delete Post By Id
DELETE {{ baseURL }}/posts/1
